//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeredeYesekDBEntities3 : DbContext
    {
        public NeredeYesekDBEntities3()
            : base("name=NeredeYesekDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grup> Grups { get; set; }
        public virtual DbSet<Istatistik> Istatistiks { get; set; }
        public virtual DbSet<Puan> Puans { get; set; }
        public virtual DbSet<Restoran> Restorans { get; set; }
        public virtual DbSet<Uyeler> Uyelers { get; set; }
    }
}
