//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puan
    {
        public int RID { get; set; }
        public int UID { get; set; }
        public int GID { get; set; }
        public int Puan1 { get; set; }
        public int PID { get; set; }
    
        public virtual Grup Grup { get; set; }
        public virtual Restoran Restoran { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
