//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restoran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restoran()
        {
            this.Puans = new HashSet<Puan>();
        }
    
        public int RID { get; set; }
        public string RestoranAdi { get; set; }
    
        public virtual Istatistik Istatistik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puan> Puans { get; set; }
    }
}
