//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istatistik
    {
        public int RID { get; set; }
        public int GidilecekGun { get; set; }
        public int GidilenGun { get; set; }
    
        public virtual Restoran Restoran { get; set; }
    }
}
